services:
  multimatics-devel:
    container_name: multimatics-devel
    build:
      context: .
      dockerfile: dockerfile.php.devel
    volumes:
      - .:/home/vscode/workspace
    command: sleep infinity
    networks:
      - multimatics-devel-network

  multimatics-postgres:
    container_name: multimatics-postgres
    image: postgres:16-alpine
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT:-5432}
    networks:
      - multimatics-devel-network

  multimatics-mysql:
    container_name: multimatics-mysql
    image: mysql:8-debian
    restart: always
    env_file: .env
    ports:
      - ${MYSQL_PORT:-3306}:${MYSQL_PORT:-3306}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - multimatics-devel-network

networks:
  multimatics-devel-network:
    name: multimatics-devel-network
    driver: bridge