FROM mcr.microsoft.com/devcontainers/go:1-1.23-bookworm

ARG NODE_VERSION=20

# download and install nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - \
    && apt-get install -y nodejs

# install typescript
RUN npm install -g typescript