FROM mcr.microsoft.com/devcontainers/php:8-bookworm

ARG NODE_VERSION=20

# download and install nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - \
    && apt-get install -y nodejs

# install typescript
RUN npm install -g typescript

# install laravel
RUN composer global require laravel/installer