basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a Gin application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin Swagger Example API
  version: "1.0"
paths:
  /export:
    get:
      description: Export transaction data to XLSX and TXT files
      produces:
      - text/plain
      responses:
        "200":
          description: Data exported successfully
          schema:
            type: string
        "500":
          description: Error querying database" or "Error scanning rows" or "Error
            saving file" or "Error creating file
          schema:
            type: string
      summary: Export transaction data
      tags:
      - transactions
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file to the server
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload a file
swagger: "2.0"
